run_clean_data:
	@printf "<<< Running .... >>>\n\n"
	@cd clean_data; python run.py
	@printf "\n\n<<< End .... >>>\n"
run_range:
	@printf "<<< Running .... >>>\n\n"
	@cd range; python run.py
	@printf "\n\n<<< End .... >>>\n"
